### ISSUE TITLE
[Suggestion] Event on attached inventory peripheral change

### ISSUE THREAD

**Issue by powerboat9** [SwitchCraftCC/Plethora-Fabric#100]
This would allow programs to assume attached inventories have not changed, and would reduce the need for periodic checks of inventory contents. The event could be debounced to once per tick if necessary.

**Comment by scmcgowen** [comment]
Considering that inventory methods are on base CC, that would be a better place to suggest this most likely

**Comment by piprett** [comment]
> Considering that inventory methods are on base CC, that would be a better place to suggest this most likely

See https://github.com/cc-tweaked/CC-Tweaked/issues/1589
