### ISSUE TITLE
Crash upon equipping neural interface in goggle trinket slot

### ISSUE THREAD

**Issue by spode-sleep** [SwitchCraftCC/Plethora-Fabric#105]
[crash-2024-08-22_01.33.42-server.txt](https://github.com/user-attachments/files/16695511/crash-2024-08-22_01.33.42-server.txt)

**Comment by SquidDev** [comment]
Plethora is currently incompatible with CC:T 1.112 or later. Afraid you'll need to downgrade to CC:T 1.111 for now.
