### ISSUE TITLE
Canvas3d create() wrong arguments expected.

### ISSUE THREAD

**Issue by Wojbie** [SwitchCraftCC/Plethora-Fabric#11]
In 1.12.2 plethora this function expected a table:
![obraz](https://user-images.githubusercontent.com/5893536/213871735-77e48ad5-407a-4305-bd30-389ad88376e7.png)
But currently it seems to expect 3 numbers:
![obraz](https://user-images.githubusercontent.com/5893536/213871704-c9f84090-6b22-4735-9979-c65d0d39d45e.png)

Related parts of code:
https://github.com/SwitchCraftCC/Plethora-Fabric/blob/68483d0d5dee1956c1fe549b27ec20bdc6c98eed/src/main/java/io/sc3/plethora/gameplay/modules/glasses/canvas/Canvas3dMethods.kt#L17-L22
https://github.com/SquidDev-CC/plethora/blob/77f1c5ad2137625506e197562636eaa689299fa5/src/main/java/org/squiddev/plethora/gameplay/modules/glasses/methods/MethodsCanvas3D.java#L28-L32

**Comment by Lemmmy** [comment]
Should be OK to fix this, the owner of computer #209 on SC3 will need to update their program though
![image](https://user-images.githubusercontent.com/858456/213871906-6225beb3-dadd-4221-8140-6c0c5de85adf.png)
