### ISSUE TITLE
2d text elements cause hotbar to solidify

### ISSUE THREAD

**Issue by Allymonies** [SwitchCraftCC/Plethora-Fabric#13]
If you add a text component to a canvas, the hotbar will no longer be partially transparent.

Steps to reproduce:
```
modules = peripheral.wrap("back")
canvas = modules.canvas()
canvas.addText({1, 1}, "Test", 0xFFFFFFFF)
```

![p1738 1](https://user-images.githubusercontent.com/7727003/213939988-02d3776d-c72b-455d-8582-9bac877005e3.jpg)
![oxuyy 1](https://user-images.githubusercontent.com/7727003/213939983-f7317e88-6a03-4e90-b009-0e3da0f69e77.jpg)

**Comment by Lemmmy** [comment]
81d431a1121ca2289d3d766496372bb6d9fa06e3 fixes this, but I'm not satisfied with it - `setupFlat` already enables blending at the start of Text2d's render method (and all other objects):

https://github.com/SwitchCraftCC/Plethora-Fabric/blob/e33cead4d801694fb6da602bc307cc09d52581b4/src/main/java/io/sc3/plethora/gameplay/modules/glasses/objects/BaseObject.kt#L85-L90

But nothing I can find in textRenderer will *disable* blending. So, unless I'm missing something, I'm not fully confident that re-enabling blending at the end of Text2d is the correct state to leave the renderer in. Perhaps some of the other methods involved (like tex2d) disable blending as a side effect, I don't actually know.

This could just be a side effect of Overlay Glasses using immediate rendering. As prep for holograms, I do need to make all the methods use the vertex consumers instead, which could either resurface issues similar to this or squash them all entirely.

When this fix makes it into a release, let me know if you find any similar issues with improper render state.
