### ISSUE TITLE
Crash right after install the mod

### ISSUE THREAD

**Issue by vico93** [SwitchCraftCC/Plethora-Fabric#16]
Hello!

I'm starting to assemble again my modpack for 1.19.3, tried to place CC:Restitched, Plethora and its dependencies on the folder and tried to run the game with that (plus FAPI and mod menu).

But i got a crash, [here](https://gist.github.com/vico93/927bf707295a0ffe3815e72850c7a3c8)'s the log.

## Specs
Minecraft 1.19.3
Fabric Loader 0.14.13
Fabric API 0.73.0
Mod Menu 5.0.2
Plethora 1.4.1
Trinkets 3.5.1
Fabric Language Kotlin 1.9.0+kotlin.1.8.0
OpenJDK 64-Bit Server VM 17 (JRE shipped with Mojang's launcher)
Windows 10 22H2 x64

**Comment by SquidDev** [comment]
Plethora requires the Fabric version of CC: Tweaked, not CC: Restitched. This is not officially available yet, though can be downloaded from [the a recent CI build](https://github.com/cc-tweaked/CC-Tweaked/actions/runs/3999426718).

This will be handled a little better once MC 1.19.4 is out, as CC:T will have a stable Fabric build.

**Comment by vico93** [comment]
> Plethora requires the Fabric version of CC: Tweaked, not CC: Restitched. This is not officially available yet, though can be downloaded from [the a recent CI build](https://github.com/cc-tweaked/CC-Tweaked/actions/runs/3999426718).
> 
> This will be handled a little better once MC 1.19.4 is out, as CC:T will have a stable Fabric build.

Uh i didnt really know you were producing a build straight for Fabric. Good news tbh.

Will wait for a stable release to try Plethora. Good work with that!
