### ISSUE TITLE
feat(neuralinterface): function to poll `yaw` and `pitch`

### ISSUE THREAD

**Issue by imjamesb** [SwitchCraftCC/Plethora-Fabric#19]
There should be functions to get the yaw and pitch of a player using the neural interface.

**Comment by jmc529** [comment]
These functions can be found within 
`.getMeta___()` type functions

for example:

```
local modules = peripheral.wrap("back")
local meta = modules.getMetaOwner()
local pitch = meta.pitch
local yaw = meta.yaw
```
