### ISSUE TITLE
Kinetic Augment can't shear sheep

### ISSUE THREAD

**Issue by Allymonies** [SwitchCraftCC/Plethora-Fabric#21]
It seems that kinetic augments cannot shear sheep, this means that it is impossible to automate sheep shearing, as shears are not a valid turtle upgrade.
![jg6eh 1](https://user-images.githubusercontent.com/7727003/215308959-ad0c3ef2-3e47-440b-aa27-082736d00678.png)
![l4dat 1](https://user-images.githubusercontent.com/7727003/215309044-e77dd050-1a5e-4360-b48e-622f3e0e4e26.png)

**Comment by SquidDev** [comment]
You should be able to call `turtle.place` with the shears. We [even have a test for it](https://github.com/cc-tweaked/CC-Tweaked/blob/1e3a930543bae0e94cd1eff70bdbcedbe141f0f9/projects/common/src/testMod/kotlin/dan200/computercraft/gametest/Turtle_Test.kt#L53-L66)!

That said, this probably still is a bug - I'd definitely expect it to work!

**Comment by DukeAbigor** [comment]
this might be another case where the raytrace in kinetic augments is failing

**Comment by Lemmmy** [comment]
I do recommend calling `turtle.place` with the shears in the future!
