### ISSUE TITLE
Combine the item name of plethora:module_scanner with the peripheral name plethora:scanner

### ISSUE THREAD

**Issue by stealthy-coder** [SwitchCraftCC/Plethora-Fabric#22]
Basicly, when finding a block scanner its identified as 'plethora:scanner' but the item name in the inventory is called 'plethora:module_scanner' which makes it harder to equip it and use the same name to peripheral.find it.

**Comment by Lemmmy** [comment]
I see that you resolved your differences with this difference in-game. For future reference, you can use the `peripherals` program to get valid peripheral names.

For a neural interface, the peripheral is `neuralInterface`:
![javaw_cSXkJ8hW5R](https://user-images.githubusercontent.com/858456/215334421-8f54e8b4-7830-4bab-9ece-b46507d98dfc.png)

For a manipulator, the peripheral is `manipulator`:
![javaw_TltpbFUzEU](https://user-images.githubusercontent.com/858456/215334431-8d39e39f-d41a-4101-9095-de82aa29c5b5.png)

For a turtle, the peripheral is the module name as shown in `.listModules()`:
![javaw_i1SWJE3tPD](https://user-images.githubusercontent.com/858456/215334437-67bb8648-412c-4acc-9b2a-ebfb9d678478.png)

I agree that this difference is a little confusing, but it would likely be a breaking change to do anything about it now.
