### ISSUE TITLE
Feat: Add peripheral methods to bee hives and nests

### ISSUE THREAD

**Issue by jmc529** [SwitchCraftCC/Plethora-Fabric#25]
I think it would be cool to get data from beehives and nests such as honey level 0-5 and bee occupants 0-3.
Additionally, it would be useful to allow players to interact with these blocks in a similar manner vanilla dispensers work to harvest honey/wax.

**Comment by Wojbie** [comment]
You can use `turtle.inspect()` call to find honey level
![obraz](https://user-images.githubusercontent.com/5893536/215885352-e3fee3cf-684e-45f0-9b87-3643e64b246b.png)
Sadly it don't display bees in hive it seems (this one had 3 bees in it)

You can use kinetic module on turtle to `.use()` shears or bottle on beehive to harvest wax/honey.

**Comment by Lemmmy** [comment]
Is block state exposed via the block scanner?

**Comment by jmc529** [comment]
It is exposed with the scanner. Sorry for not checking either of these tools before posting.
That being said, I think including bee occupants would be a nice addition to the state field.
