### ISSUE TITLE
A moudle has changed

### ISSUE THREAD

**Issue by piguman3** [SwitchCraftCC/Plethora-Fabric#26]
While a program wrapping the overlay glasses is run and it initializes the canvas3d, and .create()s it, if the module is removed, and a line tries to use any of the functions of the object the line will report an error saying:

`"A moudle has changed"` 

I haven't tested if this can happen in other ways, but it had never happened with any other module that I know of.

![imagen](https://user-images.githubusercontent.com/113848275/216217507-549b8019-5ee1-4470-8f5c-02432b60e216.png)

**Comment by Lemmmy** [comment]
To be clear, you're reporting the typo and not the fact the error happens, right?

**Comment by piguman3** [comment]
> To be clear, you're reporting the typo and not the fact the error happens, right?

Yes, I am reporting the typo sorry for not clarifying it.
