### ISSUE TITLE
Turtle inventory not updating after kinetic.use()

### ISSUE THREAD

**Issue by pajotg** [SwitchCraftCC/Plethora-Fabric#28]
When using `kinetic.use()` with a water/glass bottle on a cauldron and using `turtle.getItemDetail()` to see what the resulting item is still returns the old item

test code to reproduce:
```lua
local kinetic = peripheral.find("plethora:kinetic")

print("item detail before:", turtle.getItemDetail().name)
kinetic.use()
print("item detail after:", turtle.getItemDetail().name)
sleep(1)
print("item detail after 1s:", turtle.getItemDetail().name)
turtle.transferTo(turtle.getSelectedSlot())
print("item detail after transfer:", turtle.getItemDetail().name)
```

currently this prints out the same thing over and over until the the `turtle.transferTo()` call, even though it does absolutely nothing

**Comment by Wojbie** [comment]
Could be related to changes in `turtle.getItemDetail()` logic in latest CC:T commits.

**Comment by SquidDev** [comment]
Should probably call `setDirty` when unloading the turtle inventory:

https://github.com/SwitchCraftCC/Plethora-Fabric/blob/b1c3885114c675df774cda9c04681395c115aeef/src/main/java/io/sc3/plethora/integration/computercraft/TurtleFakePlayerProvider.java#L104
