### ISSUE TITLE
[Suggestion] Chat module

### ISSUE THREAD

**Issue by Vap0r1ze** [SwitchCraftCC/Plethora-Fabric#34]
Like the chat module from the Forge mod (linked to a player). Ideally this is how I'd implement it if i was being cautious of abuse, but could be implemented another way.
- Can send as many local messages to the player as it wants (configurable ratelimit)
- Can transform a sent message to (would allow text messages to be transformed into commands, eg: `real` -> `/r real`)
- Can prevent a message from being recieved[^1]
- Local messages could also be sent as raw message packets[^2] or, at least something more low-level than just text.[^3]

[^1]: This doesn't seem straight forward, might have to have a method for explicitly *allowing a message to be received*
[^2]: This would be good for SC3 support I think? I'm not sure because I can't find the source code for SC3's chat
[^3]: This could also just not be implemented since Overlay Goggles are a thing.

**Comment by Lemmmy** [comment]
If Chat Recorders were brought back to the mod they would still be disabled on SC3 anyway much like on SC2, in favour of the licensed chatbox system, which already handles capturing, moderation, permissions, rate limiting and audit logging; so don't worry about SC3 here

**Comment by scmcgowen** [comment]
I would love having Chat Recorders in the mod. Also would love a forge 1.19.2 port but that would be difficult to do

**Comment by Vap0r1ze** [comment]
> If Chat Recorders were brought back to the mod they would still be disabled on SC3 anyway much like on SC2, in favour of the licensed chatbox system, which already handles capturing, moderation, permissions, rate limiting and audit logging; so don't worry about SC3 here

Unfortunately the chatbox feature isn't very ergonomic and always requires a prefix. I simple use case for this would be to go into something like "reply mode" so that you don't have to remember to type `/r` every time you send a message as it's way too easy to forget

**Comment by Lemmmy** [comment]
If this issue is for /r on SwitchCraft then it would be better suited for the issue tracker there rather than a feature request for a mod that will just get disabled anyway. We have no intention of enabling chat capturing or chat recorders of any form on SC3.

Chat tabs for SC3 have been on the backburner for a while but they are not a priority.

**Comment by Vap0r1ze** [comment]
It isn't just for `/r` but rather any command that can be called repeatedly, or even a custom chat renderer. Since it seems unshakeable It seems this is rather the job of a client mod

**Comment by Wojbie** [comment]
I think there is a little bit of misunderstanding here.

If you have problem with chatbox system on SC3 then please make your report to [SC3 issue board](https://github.com/SwitchCraftCC/issues) where it can be handled properly. This is not proper venue for that discussion. 

As for plethora, [chat recorder](https://plethora.madefor.cc/items/module-chat.html) is one of features of mod that have not been ported yet. If anyone wants to help with development of this port, and they have free time to port this feature (or any other unported ones) PRs are open. One can find list of features that are not planned to be ported at [gameplay  changes list](https://docs.sc3.io/whats-new/plethora.html#gameplay-changes) in faq linked in README.md. Thanks for any who find time.

I hope this clarification clears things up.

**Comment by Vap0r1ze** [comment]
@Wojbie ohh I'm not sure how I missed that in their original response, my bad. And thank you both ^^
