### ISSUE TITLE
bug: Turtle can occupy bed

### ISSUE THREAD

**Issue by piprett** [SwitchCraftCC/Plethora-Fabric#39]
A turtle can occupy a bed with the help of kinetic augument.
The day does not pass, but no-one can use the bed as it is "occupied"
![image](https://user-images.githubusercontent.com/49862976/222946494-0ada2549-5e2f-4ce9-8342-6a7e28d3bdde.png)

**Comment by Lemmmy** [comment]
Amazing.

**Comment by ghost** [comment]
I think it'd be fun to leave this as long as the bed is no longer considered occupied when the turtle moves away.

**Comment by Lemmmy** [comment]
Will be fixed when I finish switching the mods to use the new Fabric fake player API (see https://github.com/FabricMC/fabric/pull/3005#issuecomment-1504848317)
