### ISSUE TITLE
 addon api suggestion

### ISSUE THREAD

**Issue by awesomebossdj7** [SwitchCraftCC/Plethora-Fabric#40]
there should be a addon api (if there isnt one already) where you can add more features to plethora

maybe allowing different peripherals to neural interface
ex: i make a mod that adds a peripheral that can check the irl time, then i could use the plethora addon api to make it work in the neural interface

also allowing creation of new modules
I seen that when you do listModules() it has plethora's mod name before the module name
ex: a addon mod (using the addon api) creates a new module that can make shulker boxes in your inventory, wrap as a peripheral

ideas for new modules could be endless!

**Comment by awesomebossdj7** [comment]
another module ex:
crafting module, makes your crafting table in your inventory bigger, and also acts like a crafting table for a computer to interact with

would also work on the manipulator

**Comment by SquidDev** [comment]
> if there isnt one already

[There is one](https://github.com/SwitchCraftCC/Plethora-Fabric/tree/1.19.3/src/main/java/io/sc3/plethora/api)
