### ISSUE TITLE
Transparent viewmodel when holding the block scanner.

### ISSUE THREAD

**Issue by TTHHKKYY** [SwitchCraftCC/Plethora-Fabric#45]
When holding the block scanner in your primary, or off hand, your viewmodel will become transparent, and experience
lighting issues.

![2023-03-26_19 10 35](https://user-images.githubusercontent.com/67774703/227818080-0f203ea7-2e5d-4785-a4be-409928864aad.png)

**Comment by Lemmmy** [comment]
looks like a cool potential cosmetic effect
