### ISSUE TITLE
Laser positions are not interpolated.

### ISSUE THREAD

**Issue by TTHHKKYY** [SwitchCraftCC/Plethora-Fabric#46]
Laser positions are not interpolated in both singleplayer and multiplayer.

https://user-images.githubusercontent.com/67774703/227830634-91edeeca-0e92-4f01-b675-9e34c21ad9a2.mov

**Comment by Lemmmy** [comment]
Likely a registration issue, this should also be using Fabric's EntityType builder: https://github.com/SwitchCraftCC/Plethora-Fabric/blob/defe57a10c00769605d747b56b6d105eb09a2053/src/main/java/io/sc3/plethora/gameplay/registry/Registration.java#L82-L85
