### ISSUE TITLE
[1.19.3] Game crashes trying to install the mod, all dependencies are installed

### ISSUE THREAD

**Issue by calship** [SwitchCraftCC/Plethora-Fabric#48]
Hey I dying to try the mod but the game just crashes when the it is present. I think I have all the required mods and their versions, would love if anyone can help me out :)

I'm loading the following for MC 1.19.3:
  Plethora 1.4.7
  Fabric loader 0.14.17
  Fabric API 0.75.1+1.19.3
  Fabric Language Kotlin 1.9.3+kotlin.1.8.20
  CC: Restitched 1.102.0
  Trinkets 3.5.1

Crash file:
[crash-2023-04-07_14.56.47-client.txt](https://github.com/SwitchCraftCC/Plethora-Fabric/files/11181258/crash-2023-04-07_14.56.47-client.txt)

**Comment by Lemmmy** [comment]
This mod is for [CC: Tweaked](https://modrinth.com/mod/cc-tweaked), not CC: Restitched.

**Comment by Kan18** [comment]
Related: https://github.com/SwitchCraftCC/Plethora-Fabric/issues/16#issuecomment-1403942132
You will have to download the CC: Tweaked jar from CI ([direct link](https://github.com/cc-tweaked/CC-Tweaked/suites/10558967613/artifacts/525348774)) if you plan on staying on 1.19.3

**Comment by Lemmmy** [comment]
It's on Modrinth.

**Comment by calship** [comment]
Aw thank you, sadly it looks like there's no CC: Tweaked for fabric and 1.19.3

**Comment by Lemmmy** [comment]
> Aw thank you, sadly it looks like there's no CC: Tweaked for fabric and 1.19.3

https://github.com/SwitchCraftCC/Plethora-Fabric/issues/16#issuecomment-1403942132

**Comment by calship** [comment]
Ah, thank youu, love you all!

**Comment by znepb** [comment]
This really should be mentioned in the readme

**Comment by Lemmmy** [comment]
![image](https://user-images.githubusercontent.com/858456/230697514-4cf1587b-2453-4591-b192-78d17bba20ac.png)

**Comment by znepb** [comment]
Seems kinda subtle, but I guess it's there.
