### ISSUE TITLE
Owner Meta motion is 0 if player doesn't change Y

### ISSUE THREAD

**Issue by Ale32bit** [SwitchCraftCC/Plethora-Fabric#52]
The values of `motionX` and `motionZ` are 0 if the player doesn't move in the Y axis.

`motionY` should also be `0`, but is `-0.07840000152587890680511151231257827021181583404541015625` instead.

**Comment by hugeblank** [comment]
> Yes. It's the wrong velocity object entirely.

Pulling this comment from the duplicate, what is the *correct* place to get the velocity? I was thinking maybe I could make a mixin in `Entity` that hangs onto the `pos` before it gets updated later in the same tick, but that didn't seem to work.
