### ISSUE TITLE
Owner Meta motionY is not 0 while player doesn't move in the Y axis

### ISSUE THREAD

**Issue by Ale32bit** [SwitchCraftCC/Plethora-Fabric#53]
The `motionY` variable of the owner meta should be 0 if the player doesn't move in the Y axis, but instead it has this value: `-0.07840000152587890680511151231257827021181583404541015625`.

**Comment by Lemmmy** [comment]
Duplicate of #52

**Comment by Ale32bit** [comment]
This looks like a different problem but correlated to it.
Are you sure?

**Comment by Lemmmy** [comment]
Yes. It's the wrong velocity object entirely.
