### ISSUE TITLE
suggestion to add durability to metadata of entity scanned equipment

### ISSUE THREAD

**Issue by Trickster29** [SwitchCraftCC/Plethora-Fabric#57]
When you ordinarily use an entity scanner and try to see the armor/equipment metadata of a entity. it'll just give you information about what they are wearing, but I think it would be cool and useful to know how close to breaking what they are wearing is, I unfortunately do not know how to code this myself as I am unsure how to make it universal for energy armors and regular armors alike, although I do know its possible because if you get the itemDetail when the item you're trying to get the durability for in a chest, it will show you durability. 

I would just like this key available when scanning using the Entity Scanners armor/held item/etc section.

**Comment by Lemmmy** [comment]
Sorry for the late response to this. You can get this information, you just have to call `.getMetadata()` on the item stack:

![Image](https://github.com/SwitchCraftCC/Plethora-Fabric/assets/858456/be1807f1-3ead-45da-b27f-a929607a274d)
