### ISSUE TITLE
[Bug?] Fire Resistant mobs do not take any damage from laser hits

### ISSUE THREAD

**Issue by scmcgowen** [SwitchCraftCC/Plethora-Fabric#61]
While they should be immune to afterburn (which seems to also be broken (lasting only about one game tick)), they should not be immune to the initial contact damage from the laser projectile

Expected Behavior:
Similar to flame arrow: Deals contact damage then the mob ignores the afterburn

How to reproduce:
Get laser
Fire laser at a blaze or almost any mob in the nether
see that they take 0 damage

**Comment by Lemmmy** [comment]
I don't think this is a bug? Flame arrows deal contact damage because they're...arrows. A laser beam isn't an arrow

**Comment by scmcgowen** [comment]
I believe It should deal the contact damage to fire resistant mobs since its a laser that can instantly vaporize an unarmored player.
not just set them on fire, instantly vaporize them.

**Comment by hugeblank** [comment]
technically speaking fire (mob) + fire (laser) = bigger, hotter fire. Therefore the issue here is that fire resistant mobs do not gain anything when being hit by lasers. They should be given a strength effect for a short duration when being hit, IMO.

edit - checked the commit. lmao.
