### ISSUE TITLE
[Suggestion] - Laser ability to disable block damage

### ISSUE THREAD

**Issue by scmcgowen** [SwitchCraftCC/Plethora-Fabric#65]
add a new optional parameter to the laser.fire() method to set whether the laser breaks blocks (true means it does break blocks, and is the default, while false prevents the laser from damaging blocks) This would be useful for combat laser software when you don't want stray lasers (e.g. you miss the target) from damaging the terrain

This would likely be able to be implemented via PR if accepted

**Comment by Lemmmy** [comment]
The plan for the laser rework, documented in Discord, is to have separate focusing modes for the laser based on a different item - one for entity damage and the other for block damage

**Comment by scmcgowen** [comment]
Where is this documented?

**Comment by Lemmmy** [comment]
Somewhere in Discord

**Comment by Lemmmy** [comment]
Upon reflection, I don't think lasers are going to see any kind of overhauls anytime soon.
