### ISSUE TITLE
[Suggestion] Player bindable keyboards

### ISSUE THREAD

**Issue by Ale32bit** [SwitchCraftCC/Plethora-Fabric#69]
Make keyboards bindable to players (via shift + right click, like introspection module), so computers connected to a manipulator with the bound keyboard receive key events from the player remotely.

Maybe even implement a method to start registering key events from the keyboard.

**Comment by Wojbie** [comment]
Sounds like something one could simply create using off-hand pocket mode and some lua code?

**Comment by Ale32bit** [comment]
> Sounds like something one could simply create using off-hand pocket mode and some lua code?

Unfortunately, pocket computers can only hold one peripheral at a time, my project needs to move some items around my inventory and chests.

**Comment by SquidDev** [comment]
I think what Wojbie is proposing is you have a pocket computer with modem, which talks to your main computer. That's definitely the way I'd do this.

**Comment by Ale32bit** [comment]
> I think what Wojbie is proposing is you have a pocket computer with modem, which talks to your main computer. That's definitely the way I'd do this.

That would mean I have to open the computer GUI, what I am asking is specifically the keyboard module behaviour when it's installed as a module in the neural interface, but bindable so I can install it on a manipulator.

**Comment by SquidDev** [comment]
Can you not put a modem in the neural interface then?

**Comment by Ale32bit** [comment]
> Can you not put a modem in the neural interface then?

Yes I can, but I use multishell in my NI and if I forget to focus on the right tab it will not work and mess with the other programs too.

**Comment by Lemmmy** [comment]
Thanks for the suggestion. We'll keep it in mind for the future, but right now we're quite happy with the simplified keyboard behavior. There's a less confusing combination of functionality, less to implement and maintain, and less security/claim risks to manage (even though we did already have one!). My biggest concern with this is that there would no longer be a 1:1 mapping between keyboards and computers - one key press could trigger many events on many computers, which is a little on the OP side even for Plethora.

It does sound like your use case can be covered by creatively combining the existing functionality in the mods, which is what the game is about after all. Pocket computers have a lot of potential that people seldom tap into!
