### ISSUE TITLE
Modules no longer stackable

### ISSUE THREAD

**Issue by Kan18** [SwitchCraftCC/Plethora-Fabric#7]
Plethora modules (laser, sensor, scanner, etc.) are no longer able to be stacked. This is a deviation from 1.12 behavior, where, if I recall correctly, they had a maximum stack size of 64. This makes storing large quantities of modules slightly inconvenient, since each individual module item needs its own slot in an inventory. For example:
![](https://cdn.discordapp.com/attachments/1057706496579883088/1058758358896742460/image.png)

**Comment by Lemmmy** [comment]
https://github.com/SwitchCraftCC/Plethora-Fabric/blob/68483d0d5dee1956c1fe549b27ec20bdc6c98eed/src/main/java/io/sc3/plethora/gameplay/registry/Registration.java#L185

**Comment by ShreksHellraiser** [comment]
`list` on the chest peripheral should show the NBT hashes
