### ISSUE TITLE
1.19.2 Release

### ISSUE THREAD

**Issue by Soulrel** [SwitchCraftCC/Plethora-Fabric#73]
Hey!

I made a modpack for a few friends, and one of them asked for this addon for CC: Restitched, however the only listed versions are for 1.19.3 and above. I was wondering if y'all were considering making a 1.19.2 release. I know there were quite a bit of changes to the code from 19.2 to 19.3, so if this is too much of a hassle for little benefit I understand completely. Please let me know! Thanks for your time.

**Comment by Lemmmy** [comment]
Thanks for your report. Unfortunately, this mod is only for CC: Tweaked (not Restitched) 1.19.3 and above. With other commitments the chances of a backport are low but I'll update this issue if that ever changes.
