### ISSUE TITLE
(BUG) Ancient Debris does not show up when holding a block scanner

### ISSUE THREAD

**Issue by EmmaKnijn** [SwitchCraftCC/Plethora-Fabric#74]
Ancient Debris does not show up when holding a block scanner, all other ores do.
![2023-08-04_14 03 22](https://github.com/SwitchCraftCC/Plethora-Fabric/assets/64010592/151c2285-e343-4886-aa64-01539cbd9bb9)

**Comment by EmmaKnijn** [comment]
https://github.com/SwitchCraftCC/Plethora-Fabric/blob/32b6f25ecf3d7155bc0883b0fe869cfdfe3e68cd/src/main/java/io/sc3/plethora/util/config/PlethoraConfig.kt#L93

It looks like its intended to show up according to the config

**Comment by Wojbie** [comment]
https://github.com/SwitchCraftCC/Plethora-Fabric/commit/09292d167327e06175e59ab2eee3f9bc785e8e48 It seems to have been removed on purpose in this commit as it was set to only show ores. You can see debris is commented out.

**Comment by EmmaKnijn** [comment]
Hmm I see, so its intended behavior then?
