### ISSUE TITLE
Crash when using the Neural interface remote

### ISSUE THREAD

**Issue by Compilatron144** [SwitchCraftCC/Plethora-Fabric#80]
Heyo - just wanted to say I'm glad to see Plethora is being worked on again; Love this addon for it's powerful additions to the CC interface.

Anyway - I've been trying it out, and I've gotten a crash upon using the Neural Interface Remote. This happened twice under the same conditions. I've linked the crash report as well. Hope it's of any help!

https://pastebin.com/NXF771sd

**Comment by Kan18** [comment]
Try downgrading your CC:T version to 1.106.1.

**Comment by Compilatron144** [comment]
> Try downgrading your CC:T version to 1.106.1.

Cheers - it seems to function now, although still a problem that might need to be looked into in the future.

**Comment by SquidDev** [comment]
This is fixed in #79. We were holding off merging this as SwitchCraft hasn't updated to 1.108 yet, but maybe we should do so anyway.
