### ISSUE TITLE
[Suggestion] Item NBT on Overlay Glasses

### ISSUE THREAD

**Issue by Selim042** [SwitchCraftCC/Plethora-Fabric#81]
Would be handy if you can supply NBT when adding items to the overlay.  Could include data for SC-Peripherals prints/posters, enchantment glint, armor trims, etc.  Earlier versions supported item meta values which sort of had a similar effect.

**Comment by Lemmmy** [comment]
The problem is that meta values are pretty much always sanitised and safe by default, whereas NBT is nontrivial to ensure it won't immediately crash the game, be compatible with everything, etc. This is unlikely to be supported
