### ISSUE TITLE
Neural Interface cannot accept pocket computer upgrades.

### ISSUE THREAD

**Issue by walksanatora** [SwitchCraftCC/Plethora-Fabric#86]
it just makes sense (in my mind) for neural interface to be able to accept pocket computer upgrades)

**Comment by Lemmmy** [comment]
Are you referring to peripherals? It already accepts them in the first five slots. Is there a particular modded upgrade you're having trouble with?

**Comment by walksanatora** [comment]
I am writing a CC addon that registers a pocket/turtle only specitic upgrade on the `hexcasting:staff/mindsplice`
but when I try to insert it to any module/peripheral slots it gets rejected. and this is more of a matter of feeling. cause to me it just "feels better" if the NI is able to equip pocket computer upgrades (due to using a pocket computer in the crafting recipe)

**Comment by Lemmmy** [comment]
Ah, I see. Have you added the item ID to "peripheral item IDs" in the Plethora config? [By default](<https://github.com/SwitchCraftCC/Plethora-Fabric/blob/0513a48a9e2fc0155bf9c471ab0714b48ff3c4ba/src/main/java/io/sc3/plethora/util/config/PlethoraConfig.kt#L140-L148>) it only allows the three vanilla peripherals.

Apologies if the syntax is incorrect, writing from mobile:

```hocon
neural-interface {
  peripheral-item-ids: [
    computercraft:speaker
    computercraft:wireless_modem_normal
    computercraft:wireless_modem_advanced
    # Your peripheral here:
    hexcasting:staff/mindsplice
  ]
}
```

**Comment by walksanatora** [comment]
so I have
```
neural-interface {
    # List of pocket upgrade item IDs that can be used in neural interface as peripherals.
    peripheral-item-ids=[
        "computercraft:speaker",
        "computercraft:wireless_modem_normal",
        "computercraft:wireless_modem_advanced",
        "hexcasting:staff/mindsplice"
    ]
}
```
![image](https://github.com/SwitchCraftCC/Plethora-Fabric/assets/47339836/e23c27a0-d092-4738-a735-0227945de25f)

yet I tried to /reload and leave/enter world but it would not let me place it in. gonna try re-opening minecraft to test again

**Comment by walksanatora** [comment]
(and is there a way to automatically add my peripheral to the default)

**Comment by walksanatora** [comment]
also full restart. I still cant put the mindsplice staff into the NI

**Comment by walksanatora** [comment]
wait... I think I am using a outdated version of my mod lemme update it ...

**Comment by Lemmmy** [comment]
> (and is there a way to automatically add my peripheral to the default)

No, not currently.

**Comment by walksanatora** [comment]
okay yeah it was my mod (on the "client test", where I just put it in prism launcher with a few other mods) I forgot to re-build it so it had the pocket data.

**Comment by walksanatora** [comment]
> > (and is there a way to automatically add my peripheral to the default)
> 
> No, not currently.

so should I re-title this issue. or make a new one

**Comment by Lemmmy** [comment]
Great, glad you got it working!

**Edit:**
> so should I re-title this issue. or make a new one

This will not be worked on.
