### ISSUE TITLE
kinetic augment .use(duration, hand) does not respect left handedness

### ISSUE THREAD

**Issue by hugeblank** [SwitchCraftCC/Plethora-Fabric#87]
1. Change your main hand from right to left in options -> skin customization -> main hand
2. Hold a pocket computer in offhand (right).
3. Create a script that sleeps for a moment, then runs `back.use(nil, "right")`
4. Notice how it does nothing, try again, this time with `back.use(nil, "left")`. It will work amid the pocket computer being in the *right* hand.

**Comment by hugeblank** [comment]
realistically this should just be a boolean value anyways, false/nil = main hand, true = offhand

**Comment by Lemmmy** [comment]
Not sure where you got "left" and "right" from, you're supposed to pass "main" or "off".

![image](https://github.com/SwitchCraftCC/Plethora-Fabric/assets/858456/d8b6e79d-3e83-4689-a426-73757bbfe807)

**Comment by Lemmmy** [comment]
![image](https://github.com/SwitchCraftCC/Plethora-Fabric/assets/858456/2aeea5e7-e2af-49ce-a1c6-6b48fdb6176f)

Suppose it wouldn't matter actually. Perhaps the skin customisation change isn't propagating to the fake player entity. Does the issue still happen after you relog? (For long enough such that the computer is terminated and really restarts)

**Comment by hugeblank** [comment]
My testing was done in a single player world. As for where I got the left/right from: https://plethora.madefor.cc/methods.html#org.squiddev.plethora.integration.vanilla.method.MethodsKineticActions-use(IModuleContainer)
I'll get back to you tomorrow on if the issue can be repeated on the SP world after a restart, as well as on the server

**Comment by hugeblank** [comment]
When using "main"/"off" the correct hand is used. This issue occurs purely because it's incorrect to assume that the main hand is the "right" hand in `ArgumentExt.kt:87`

**Comment by scmcgowen** [comment]
1. damn this is a big necro
2. I feel that at this point, correcting this issue may possibly be a breaking change considering that some people may be specifically using "right" for the main hand

**Comment by hugeblank** [comment]
1. not really, it's only been 3 and a bit months.
2. Just checked because I also was curious of this. On SC there are 0 cases of the `.use` method with "left"/"right" strings. Obviously this isn't explicit proof, but it leads me to believe that it won't be as major of a "breaking change" as you suggest.
