### ISSUE TITLE
Sideways manipulators not accepting modules

### ISSUE THREAD

**Issue by Kan18** [SwitchCraftCC/Plethora-Fabric#9]
Manipulators placed in a regular orientation work fine. However, manipulators that are sideways do not accept modules.
(alternate video link: https://cdn.discordapp.com/attachments/1057706496579883088/1064175642293321888/manipulator_sideways.mp4)

https://user-images.githubusercontent.com/24967425/212543835-e37156cf-843b-4939-91a2-b54a61bc70d4.mp4

**Comment by Lemmmy** [comment]
I believe this was updated wrong from 1.19.2 to 1.19.3 when the math lib changed

https://github.com/SwitchCraftCC/Plethora-Fabric/blob/68483d0d5dee1956c1fe549b27ec20bdc6c98eed/src/main/java/io/sc3/plethora/gameplay/manipulator/ManipulatorType.java#L44-L53

On a similar note, when this *is* fixed, the outline renderer only shows the glowing white quad for the down facing, which is something I should be able to fix here too

**Comment by Lemmmy** [comment]
I think now that sc-library has a set of Box utilities (used for 3d prints mainly), the Manipulator box methods should be rewritten to use those.
