### ISSUE TITLE
a nasty crash when having a neural interface on your gnoggin

### ISSUE THREAD

**Issue by KiloTheNeko** [SwitchCraftCC/Plethora-Fabric#93]
[crash-2024-03-23_18.54.03-server.txt](https://github.com/SwitchCraftCC/Plethora-Fabric/files/14733154/crash-2024-03-23_18.54.03-server.txt)

**Comment by Lemmmy** [comment]
This is already fixed by adb6553477508bc2f748c1a111b3ac6767963a8b. Until the latest version of Plethora is released (hopefully within the next few days), it will not be compatible with CC: Tweaked 1.110.0 or 1.110.1. Please either downgrade CC:T or hold out for the next Plethora release!

**Comment by Lemmmy** [comment]
1.11.0 is now out, which should fix compatibility with CC:T 1.110.1.
